### ISSUE TITLE
pga sim issue

### ISSUE THREAD

**Issue by Shiner36** [chanzer0/PGA-DFS-Tools#10]
I am receiving this error when attempting to run the pga sim. I am a noob when it comes to this, is it saying it isn't finding fantasy points? I read the read me so I am not sure where I screwed up. Thanks in advance

PS C:\Users\bshin\Desktop\PGA-DFS-Tools-main\src> python .\main.py dk sim cid file 1000
['.\\main.py', 'dk', 'sim', 'cid', 'file', '1000']
Traceback (most recent call last):
  File "C:\Users\bshin\Desktop\PGA-DFS-Tools-main\src\main.py", line 61, in <module>
    main(sys.argv)
  File "C:\Users\bshin\Desktop\PGA-DFS-Tools-main\src\main.py", line 54, in main
    sim = PGA_GPP_Simulator(site, field_size, num_iterations, use_contest_data,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bshin\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 43, in __init__
    self.load_projections(projection_path)
  File "C:\Users\bshin\Desktop\PGA-DFS-Tools-main\src\pga_gpp_simulator.py", line 170, in load_projections
    if float(row['Fpts']) < self.projection_minimum:
             ~~~^^^^^^^^
KeyError: 'Fpts'

**Comment by chanzer0** [comment]
Make sure the data source you are using has "Fpts" as the column header

**Comment by chanzer0** [comment]
in `projections.csv`

**Comment by Shiner36** [comment]
Thank you!Sent from my iPhoneOn Jun 22, 2023, at 6:48 PM, Sean ***@***.***> wrote:﻿
in projections.csv

**Comment by chanzer0** [comment]
happy to help
